### ISSUE TITLE
Remove nightly openj9 testing while we do not have fresh nightly/EA builds.

### ISSUE THREAD

**Issue by smlambert** [adoptium/run-aqa#119]
This issue describes that there is no longer a nightly openj9 build available to test, so we should remove it from the nightly test matrix.  To resolve this issue, remove openj9 from https://github.com/adoptium/run-aqa/blob/master/.github/workflows/sanity.yml#L14 

Symptoms of this issue show an on-going nightly run-aqa workflow failure:

[sanity (ubuntu-latest, 17, openj9, functional)](https://github.com/adoptium/run-aqa/runs/5131619311?check_suite_focus=true)
The process '/usr/bin/make' failed with exit code 2

**Comment by smlambert** [comment]
Right, so we should update this issue to turn off nightly testing for OpenJ9, because we can not get a nightly build of it (for now).  We could run against a release build which is still being published to AdoptOpenJDK and is available as Semeru Open Edition, but makes no sense to repeat testing nightly on something that is not changing.

**Comment by sophia-guo** [comment]
Also might just move to https://github.com/actions/setup-java

**Comment by abhijeetjejurkar** [comment]
Hii , I would like to work on this?
