### ISSUE TITLE
external tests can't get DOCKERIMAGE_TAG set

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/run-aqa#80]
external tests can't get DOCKERIMAGE_TAG set, which caused 

```
"/home/runner/work/runaqaTest/runaqaTest/openjdk-tests/TKG/../TKG/output_16173068587866/TestTargetResult";
Unable to recognize DOCKER_OS from DOCKERIMAGE_TAG = --version!
docker run  --rm adoptopenjdk-derby-test:8-jdk-ubuntu-hotspot-full 
Unable to find image 'adoptopenjdk-derby-test:8-jdk-ubuntu-hotspot-full' locally
docker: Error response from daemon: pull access denied for adoptopenjdk-derby-test, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

```
https://github.com/sophia-guo/runaqaTest/runs/2249127830?check_suite_focus=true

Need to investigate why the if condition( which should set dockerImageTag=nighlty) doesn't work https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/build.xml#L28

**Comment by sophia-guo** [comment]
`DOCKERIMAGE_TAG` works as an environment variable for external tests. For test build stage if no `DOCKERIMAGE_TAG` set [ `nightly` is used as default](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/build.xml#L34).  For test running `DOCKERIMAGE_TAG` is specifically used as [a  shell script parameter](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/camel/playlist.xml#L31`). That is for local run or run-aqa if `DOCKERIMAGE_TAG` is not set as an environment variable external tests will fail.

**Comment by sophia-guo** [comment]
[Currently locally run with external tests manual may not work](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/README.md#running-external-tests-locally). The fix will also need to update the readme

**Comment by sophia-guo** [comment]
Fix is in https://github.com/AdoptOpenJDK/openjdk-tests/pull/2462. 

Re https://github.com/adoptium/run-aqa/issues/80#issuecomment-814237556

Based on the current fix no need to update Readme.

**Comment by karianna** [comment]
@sophia-guo so this can be closed?

**Comment by sophia-guo** [comment]
Yes, it can be closed.
