### ISSUE TITLE
Add support for VENDOR_TEST_REPOS/BRANCHES/SHAS/DIRS parameters

### ISSUE THREAD

**Issue by smlambert** [adoptium/run-aqa#81]
We have the notion of laying down other repos outside of those in the AQA set.  This allows vendors to use AQA tools and overlay additional tests they have.  We also use this mechanism to add buildAndPackaging smoke tests from the build repo.

This issue is a feature request to support the use of VENDOR_TEST_REPOS, VENDOR_BRANCH, VENDOR_TEST_BRANCHES, VENDOR_TEST_SHAS, VENDOR_TEST_DIRS where each parameter is a comma-separated list of strings (that must be matched up in order in the list if listing multiples).

<img width="483" alt="Screen Shot 2021-04-27 at 6 35 58 PM" src="https://user-images.githubusercontent.com/2836948/116321078-6e6d1c00-a787-11eb-82f8-214abd4bcb2f.png">

The immediate request is so that we can add a workflow to the adoptium/temurin-build repo to run smoke tests for PR testing (without having to trigger a Jenkins job).

---------------

FYI @sophia-guo - It would be good to have your input on what needs to be done in order to support this (someone else could take the task, but you likely have the best idea of how they'd get started).

**Comment by sophia-guo** [comment]
To support those parameters we can just set those parameters as the run-aqa action inputs and  pass them to `function runGetSh`, which will call get.sh to handle the setup. The only thing need to be careful is users need to make sure comma-separated list of strings in the correct order.

**Comment by gdams** [comment]
@smlambert now this is complete, what are the steps to add this to the temurin-build action?

**Comment by sophia-guo** [comment]
@gdams it's in this PR https://github.com/adoptium/temurin-build/pull/2660
