### ISSUE TITLE
Update workflow yml files to replace jdk16 with jdk17

### ISSUE THREAD

**Issue by smlambert** [adoptium/run-aqa#98]
In yaml files inside of https://github.com/adoptium/run-aqa/blob/master/.github/workflows
where ever we reference jdk16, we should switch to jdk17

Example: https://github.com/adoptium/run-aqa/blob/master/.github/workflows/sanity.yml#L13
should be changed to `version: [8, 11, 17]`

**Comment by keerthi-kamath** [comment]
I would love to work on this!

**Comment by smlambert** [comment]
Great!  thanks @keerthi-kamath !
